# https://kubernetes.io/docs/tasks/configure-pod-container/configure-liveness-readiness-startup-probes/
apiVersion: v1
kind: Pod
metadata:
  name: etcd-with-grpc
spec:
  containers:
  - name: etcd
    command:
    - /usr/local/bin/etcd
    - --data-dir
    - /var/lib/etcd
    - --listen-client-urls
    - http://0.0.0.0:2379
    - --advertise-client-urls
    - http://127.0.0.1:2379
    - --log-level
    - debug
    image: k8s.gcr.io/etcd:3.5.1-0
    ports:
    - containerPort: 2379
    livenessProbe:
      grpc:
        port: 2379
      initialDelaySeconds: 10

## kubeadm, kubelet 필요.